apiVersion: v1
kind: PersistentVolume
metadata:
  name: nosh-db-persistentvolume
  labels:
    app: nosh-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/nosh-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nosh-db-persistentvolumeclaim
  labels:
    app: nosh-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
